services:
  - type: web
    name: job-application-tracker
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npx serve -s dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 3000
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
